#ifndef UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_H
#define UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_H

typedef enum drone_message_type {
	MOTHERSHIP_GO_DELIVER_PACKAGE,
	MOTHERSHIP_GO_RECHARGE,
	MOTHERSHIP_END_OF_DELIVERY
} DroneMessageType;

struct drone_message {
	DroneMessageType type;
};

#endif //UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_H
