#ifndef UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_HPP
#define UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_HPP

#include "typedefs.h"

enum drone_message_type{
	MOTHERSHIP_GO_DELIVER_PACKAGE,
	MOTHERSHIP_GO_RECHARGE,
	MOTHERSHIP_END_OF_DELIVERY
	//TODO
};

struct drone_message{
	DroneMessageType type;
};

#endif //UTBM_LO41_DRONEDELIVERYSYSTEM_DRONE_MESSAGE_HPP
